[phases.setup]
nixPkgs = ['python39', 'ffmpeg']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 app:app"
